# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
#image: node:latest

stages:
  - build
  - package

#before_scripts:
#  
#
#variables:
#  S3_BUCKET_NAME: "accenture-fashionpair"
#
#
# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules/

build:
  stage: build
  image: node:latest
  script:
  - npm install
  - npm install webpack yarn
  - npm run build

package:
  stage: package
  script:
  - ls -la

#deploy:
#  image: python:latest
#  environment: production
#  script:
#  - pip install awscli
#  - aws s3 cp ./client s3://$S3_BUCKET_NAME/ --recursive --exclude "*" --include "*.html"
#  only:
#  - master

#review:
#  variables:
#    S3_BUCKET_NAME: "accenture-fashionpair-dev"
#  image: python:latest
#  environment: review
#  script:
#  - pip install awscli
#  - mkdir -p ./$CI_BUILD_REF_NAME
#  - cp ./*.html ./$CI_BUILD_REF_NAME/
#  - aws s3 cp ./ s3://$S3_BUCKET_NAME/ --recursive --exclude "*" --include "*.html"

